{
  "Unit": "string",
  "Vehicle": "string",
  "Date": "date",
  "Intervention_Report": "string",
  "Intervention_Action": "string",
  "P_Symptom": "string",
  "P_Root": "string",
  "Is_Relevant": "string",
  "Master_Intervention_Key": "string",
  "Intervention_Key": "string",
  "Intervention_ID": "string",
  "Intervention_Type": "string",
  "Part_Cancellations": "integer",
  "Full_Cancellations": "integer",
  "Railway_Period": "string",
  "Fleet": "string",
  "TOC": "string",
  "Depot": "string",
  "Class": "string",
  "Sub_Class": "string",
  "Location": "string",
  "Is_TIN": "boolean",
  "Porterbrook_Asset": "boolean",
  "P_Root_Code_Inferred_Tertiary": "string",
  "P_Symptom_Inferred": "string"
}
